### ISSUE TITLE
KeyError: "Unable to open object (object 'channel_id' doesn't exist)"

### ISSUE THREAD

**Issue by siminpan** [organic-chemistry/RepNano#5]
Hi,

I'm trying to run RepNano on my own project. 

Before I do it, I'm trying to reproduce the result from your paper. 
I downloaded files from PRJEB36782. BTF_AG_ONT_1_FAH14273_A.NB12_fast5.tgz and ERR4016317_1.fastq.gz for the input.

here is the code I use for the first step:
`python /bin/RepNano/src/repnano/data/preprocess.py
  --hdf5 /RepNano_data/env/ig/atelier/nanopore/cns/MN19358/170808_MN19358_FAH14273_A/events/20170808_1308_776/fast5/0/i0013771_20170808_FAH14273_MN19358_sequencing_run_776_68918_read_100_ch_278_strand.fast5
  --fastq /RepNano_data/ERR4016317_1.fastq
  --ref /RepNano_data/GCF_000146045.2_R64_genomic.fna
  --output_name /RepNano_data/test_result/output.fast5
  --njobs 6`

here is the error message I got:
"Total number of reads 2
Traceback (most recent call last):
  File "/home/zlyrebecca/bin/RepNano/src/repnano/data/preprocess.py", line 472, in <module>
    maxlen=args.max_len,fastqs=args.fastqs)
  File "/home/zlyrebecca/bin/RepNano/src/repnano/data/preprocess.py", line 235, in process_one_big_hdf5
    id1,id2 = get_names(h5p) #depend of the formating
  File "/home/zlyrebecca/bin/RepNano/src/repnano/data/preprocess.py", line 15, in get_names
    ch = int(str(h5p["channel_id"].attrs["channel_number"])[2:-1])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zlyrebecca/anaconda3/envs/tomboenv/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'channel_id' doesn't exist)""

Could you help me with it?

Thank you!

**Comment by hennion** [comment]
Dear Simin Pan, 
you downloaded  BTF_AG_ONT_1_FAH14273_A.NB12_fast5.tgz which is a control thymidine only sample. It is an old format (before 2019) where each file contains only one read. To process those old files you have to remove the --bigf option as you did, and give the path to the folder containing the 4000 files. 
```
python /bin/RepNano/src/repnano/data/preprocess.py --hdf5 /RepNano_data/env/ig/atelier/nanopore/cns/MN19358/170808_MN19358_FAH14273_A/events/20170808_1308_776/fast5/0 --fastq /RepNano_data/ERR4016317_1.fastq --ref /RepNano_data/GCF_000146045.2_R64_genomic.fna --output_name /RepNano_data/test_result/output.fast5 --njobs 6
```
I hope this helps.
Best regards,
Magali

**Comment by siminpan** [comment]
Hi Magali,

Thank you for your input. That helps a lot. 
I tried "RepNano/src/repnano/data/preprocess.py" with a directory as input. It doesn't go through. 
I'm now following the data before 2019 instructions, tombo is running, finger crossed.

Thank you for your kind help.

Simin
